<?xml version="1.0"?>
<package format="3">
  <name>moonmapper_ml</name>
  <version>0.0.1</version>
  <description>Runtime ML inference nodes for MoonMapper (model loading and classification publishing).</description>
  <maintainer email="TODO@TODO.no">TODO</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>moonmapper_interfaces</depend>

  <exec_depend>python3</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

